-- Preserve old imported rows before creating the normalized current-position table.
ALTER TABLE "Holding" RENAME TO "ImportedHolding";
ALTER TABLE "ImportedHolding" RENAME CONSTRAINT "Holding_pkey" TO "ImportedHolding_pkey";

CREATE TYPE "DataProvider" AS ENUM ('CSV', 'PDF', 'SNAPTRADE', 'PLAID', 'MANUAL');
CREATE TYPE "ConnectionStatus" AS ENUM ('PENDING', 'CONNECTED', 'DISCONNECTED', 'ERROR', 'REQUIRES_REAUTH');
CREATE TYPE "AccountStatus" AS ENUM ('ACTIVE', 'CLOSED', 'ERROR');
CREATE TYPE "SecurityType" AS ENUM ('STOCK', 'ETF', 'MUTUAL_FUND', 'FIXED_INCOME', 'OPTION', 'CRYPTO', 'CASH', 'OTHER');
CREATE TYPE "HoldingSource" AS ENUM ('CSV_IMPORT', 'PDF_IMPORT', 'SNAPTRADE', 'PLAID', 'MANUAL');
CREATE TYPE "TransactionType" AS ENUM ('BUY', 'SELL', 'DIVIDEND', 'INTEREST', 'FEE', 'TRANSFER', 'DEPOSIT', 'WITHDRAWAL', 'SPLIT', 'OPTION_EXERCISE', 'OTHER');
CREATE TYPE "JobStatus" AS ENUM ('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED');
CREATE TYPE "InsightSeverity" AS ENUM ('INFO', 'LOW', 'MEDIUM', 'HIGH');
CREATE TYPE "InsightStatus" AS ENUM ('ACTIVE', 'DISMISSED', 'ARCHIVED');
CREATE TYPE "AlertEventStatus" AS ENUM ('PENDING', 'DELIVERED', 'FAILED', 'DISMISSED');

CREATE TABLE "DataSource" ("id" TEXT NOT NULL, "provider" "DataProvider" NOT NULL, "displayName" TEXT NOT NULL, "capabilities" JSONB, "isEnabled" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "DataSource_pkey" PRIMARY KEY ("id"));
CREATE TABLE "BrokerageConnection" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "dataSourceId" TEXT, "provider" "DataProvider" NOT NULL, "providerUserId" TEXT, "providerConnectionId" TEXT, "brokerageName" TEXT NOT NULL, "status" "ConnectionStatus" NOT NULL DEFAULT 'PENDING', "lastSuccessfulSyncAt" TIMESTAMP(3), "lastAttemptedSyncAt" TIMESTAMP(3), "syncErrorCode" TEXT, "syncErrorMessage" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "BrokerageConnection_pkey" PRIMARY KEY ("id"));
CREATE TABLE "InvestmentAccount" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "brokerageConnectionId" TEXT, "portfolioId" TEXT NOT NULL, "providerAccountId" TEXT, "name" TEXT NOT NULL, "officialName" TEXT, "maskedAccountNumber" TEXT, "accountType" TEXT NOT NULL, "accountSubtype" TEXT, "currency" TEXT NOT NULL DEFAULT 'USD', "status" "AccountStatus" NOT NULL DEFAULT 'ACTIVE', "isIncludedInAnalysis" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "InvestmentAccount_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Security" ("id" TEXT NOT NULL, "canonicalSymbol" TEXT, "providerSecurityId" TEXT, "cusip" TEXT, "isin" TEXT, "sedol" TEXT, "name" TEXT NOT NULL, "securityType" "SecurityType" NOT NULL DEFAULT 'OTHER', "exchange" TEXT, "currency" TEXT NOT NULL DEFAULT 'USD', "sector" TEXT, "industry" TEXT, "country" TEXT, "metadata" JSONB, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Security_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Holding" ("id" TEXT NOT NULL, "accountId" TEXT NOT NULL, "securityId" TEXT NOT NULL, "quantity" DECIMAL(24,10) NOT NULL, "averageCost" DECIMAL(24,10), "costBasis" DECIMAL(24,4), "currentPrice" DECIMAL(24,10), "marketValue" DECIMAL(24,4) NOT NULL, "currency" TEXT NOT NULL DEFAULT 'USD', "asOfDate" TIMESTAMP(3) NOT NULL, "source" "HoldingSource" NOT NULL, "rawProviderData" JSONB, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Holding_pkey" PRIMARY KEY ("id"));
CREATE TABLE "CashBalance" ("id" TEXT NOT NULL, "accountId" TEXT NOT NULL, "amount" DECIMAL(24,4) NOT NULL, "currency" TEXT NOT NULL DEFAULT 'USD', "asOfDate" TIMESTAMP(3) NOT NULL, "source" "HoldingSource" NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "CashBalance_pkey" PRIMARY KEY ("id"));
CREATE TABLE "InvestmentTransaction" ("id" TEXT NOT NULL, "accountId" TEXT NOT NULL, "securityId" TEXT, "providerTransactionId" TEXT, "type" "TransactionType" NOT NULL, "subtype" TEXT, "tradeDate" TIMESTAMP(3) NOT NULL, "settlementDate" TIMESTAMP(3), "quantity" DECIMAL(24,10), "price" DECIMAL(24,10), "amount" DECIMAL(24,4) NOT NULL, "fees" DECIMAL(24,4), "currency" TEXT NOT NULL DEFAULT 'USD', "description" TEXT NOT NULL, "source" "HoldingSource" NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "InvestmentTransaction_pkey" PRIMARY KEY ("id"));
CREATE TABLE "PortfolioSnapshot" ("id" TEXT NOT NULL, "portfolioId" TEXT NOT NULL, "totalValue" DECIMAL(24,4) NOT NULL, "cashValue" DECIMAL(24,4) NOT NULL, "investedValue" DECIMAL(24,4) NOT NULL, "dailyChange" DECIMAL(24,4), "dailyChangePercent" DECIMAL(18,8), "snapshotDate" TIMESTAMP(3) NOT NULL, "sourceCoverage" JSONB, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "PortfolioSnapshot_pkey" PRIMARY KEY ("id"));
CREATE TABLE "HoldingSnapshot" ("id" TEXT NOT NULL, "portfolioSnapshotId" TEXT NOT NULL, "accountId" TEXT NOT NULL, "securityId" TEXT NOT NULL, "quantity" DECIMAL(24,10) NOT NULL, "marketValue" DECIMAL(24,4) NOT NULL, "costBasis" DECIMAL(24,4), "currency" TEXT NOT NULL DEFAULT 'USD', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "HoldingSnapshot_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ImportJob" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "portfolioId" TEXT, "accountId" TEXT, "dataSourceId" TEXT, "source" "HoldingSource" NOT NULL, "status" "JobStatus" NOT NULL DEFAULT 'PENDING', "fileName" TEXT, "errorCode" TEXT, "errorMessage" TEXT, "startedAt" TIMESTAMP(3), "completedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "ImportJob_pkey" PRIMARY KEY ("id"));
CREATE TABLE "SyncJob" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "brokerageConnectionId" TEXT, "dataSourceId" TEXT, "status" "JobStatus" NOT NULL DEFAULT 'PENDING', "errorCode" TEXT, "errorMessage" TEXT, "startedAt" TIMESTAMP(3), "completedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "SyncJob_pkey" PRIMARY KEY ("id"));
CREATE TABLE "PortfolioInsight" ("id" TEXT NOT NULL, "portfolioId" TEXT NOT NULL, "type" TEXT NOT NULL, "title" TEXT NOT NULL, "summary" TEXT NOT NULL, "severity" "InsightSeverity" NOT NULL DEFAULT 'INFO', "status" "InsightStatus" NOT NULL DEFAULT 'ACTIVE', "asOfDate" TIMESTAMP(3) NOT NULL, "metadata" JSONB, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "PortfolioInsight_pkey" PRIMARY KEY ("id"));
CREATE TABLE "InsightEvidence" ("id" TEXT NOT NULL, "insightId" TEXT NOT NULL, "securityId" TEXT, "metric" TEXT NOT NULL, "value" JSONB NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "InsightEvidence_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Watchlist" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "portfolioId" TEXT, "name" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Watchlist_pkey" PRIMARY KEY ("id"));
CREATE TABLE "WatchlistSecurity" ("watchlistId" TEXT NOT NULL, "securityId" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "WatchlistSecurity_pkey" PRIMARY KEY ("watchlistId", "securityId"));
CREATE TABLE "AlertRule" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "portfolioId" TEXT, "securityId" TEXT, "type" TEXT NOT NULL, "configuration" JSONB NOT NULL, "isEnabled" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "AlertRule_pkey" PRIMARY KEY ("id"));
CREATE TABLE "AlertEvent" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "alertRuleId" TEXT, "status" "AlertEventStatus" NOT NULL DEFAULT 'PENDING', "payload" JSONB NOT NULL, "deliveredAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "AlertEvent_pkey" PRIMARY KEY ("id"));

CREATE UNIQUE INDEX "DataSource_provider_key" ON "DataSource"("provider");
CREATE UNIQUE INDEX "BrokerageConnection_userId_provider_providerConnectionId_key" ON "BrokerageConnection"("userId", "provider", "providerConnectionId"); CREATE INDEX "BrokerageConnection_userId_status_idx" ON "BrokerageConnection"("userId", "status");
CREATE UNIQUE INDEX "InvestmentAccount_userId_providerAccountId_key" ON "InvestmentAccount"("userId", "providerAccountId"); CREATE INDEX "InvestmentAccount_portfolioId_status_idx" ON "InvestmentAccount"("portfolioId", "status"); CREATE INDEX "InvestmentAccount_brokerageConnectionId_idx" ON "InvestmentAccount"("brokerageConnectionId");
CREATE UNIQUE INDEX "Security_canonicalSymbol_key" ON "Security"("canonicalSymbol"); CREATE UNIQUE INDEX "Security_providerSecurityId_key" ON "Security"("providerSecurityId"); CREATE UNIQUE INDEX "Security_cusip_key" ON "Security"("cusip"); CREATE UNIQUE INDEX "Security_isin_key" ON "Security"("isin"); CREATE UNIQUE INDEX "Security_sedol_key" ON "Security"("sedol"); CREATE INDEX "Security_name_idx" ON "Security"("name"); CREATE INDEX "Security_securityType_canonicalSymbol_idx" ON "Security"("securityType", "canonicalSymbol");
CREATE UNIQUE INDEX "Holding_accountId_securityId_key" ON "Holding"("accountId", "securityId"); CREATE INDEX "Holding_accountId_asOfDate_idx" ON "Holding"("accountId", "asOfDate"); CREATE INDEX "Holding_securityId_idx" ON "Holding"("securityId");
CREATE UNIQUE INDEX "CashBalance_accountId_currency_key" ON "CashBalance"("accountId", "currency"); CREATE INDEX "CashBalance_accountId_asOfDate_idx" ON "CashBalance"("accountId", "asOfDate");
CREATE UNIQUE INDEX "InvestmentTransaction_accountId_providerTransactionId_key" ON "InvestmentTransaction"("accountId", "providerTransactionId"); CREATE INDEX "InvestmentTransaction_accountId_tradeDate_idx" ON "InvestmentTransaction"("accountId", "tradeDate"); CREATE INDEX "InvestmentTransaction_securityId_tradeDate_idx" ON "InvestmentTransaction"("securityId", "tradeDate");
CREATE UNIQUE INDEX "PortfolioSnapshot_portfolioId_snapshotDate_key" ON "PortfolioSnapshot"("portfolioId", "snapshotDate"); CREATE INDEX "PortfolioSnapshot_portfolioId_snapshotDate_idx" ON "PortfolioSnapshot"("portfolioId", "snapshotDate"); CREATE UNIQUE INDEX "HoldingSnapshot_portfolioSnapshotId_accountId_securityId_key" ON "HoldingSnapshot"("portfolioSnapshotId", "accountId", "securityId"); CREATE INDEX "HoldingSnapshot_securityId_idx" ON "HoldingSnapshot"("securityId");
CREATE INDEX "ImportJob_userId_status_createdAt_idx" ON "ImportJob"("userId", "status", "createdAt"); CREATE INDEX "SyncJob_userId_status_createdAt_idx" ON "SyncJob"("userId", "status", "createdAt"); CREATE INDEX "PortfolioInsight_portfolioId_status_asOfDate_idx" ON "PortfolioInsight"("portfolioId", "status", "asOfDate"); CREATE INDEX "InsightEvidence_insightId_idx" ON "InsightEvidence"("insightId"); CREATE UNIQUE INDEX "Watchlist_userId_name_key" ON "Watchlist"("userId", "name"); CREATE INDEX "WatchlistSecurity_securityId_idx" ON "WatchlistSecurity"("securityId"); CREATE INDEX "AlertRule_userId_isEnabled_idx" ON "AlertRule"("userId", "isEnabled"); CREATE INDEX "AlertEvent_userId_status_createdAt_idx" ON "AlertEvent"("userId", "status", "createdAt");

ALTER TABLE "BrokerageConnection" ADD CONSTRAINT "BrokerageConnection_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE; ALTER TABLE "BrokerageConnection" ADD CONSTRAINT "BrokerageConnection_dataSourceId_fkey" FOREIGN KEY ("dataSourceId") REFERENCES "DataSource"("id") ON DELETE SET NULL;
ALTER TABLE "InvestmentAccount" ADD CONSTRAINT "InvestmentAccount_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE; ALTER TABLE "InvestmentAccount" ADD CONSTRAINT "InvestmentAccount_portfolioId_fkey" FOREIGN KEY ("portfolioId") REFERENCES "Portfolio"("id") ON DELETE CASCADE; ALTER TABLE "InvestmentAccount" ADD CONSTRAINT "InvestmentAccount_brokerageConnectionId_fkey" FOREIGN KEY ("brokerageConnectionId") REFERENCES "BrokerageConnection"("id") ON DELETE SET NULL;
ALTER TABLE "Holding" ADD CONSTRAINT "Holding_accountId_fkey" FOREIGN KEY ("accountId") REFERENCES "InvestmentAccount"("id") ON DELETE CASCADE; ALTER TABLE "Holding" ADD CONSTRAINT "Holding_securityId_fkey" FOREIGN KEY ("securityId") REFERENCES "Security"("id") ON DELETE RESTRICT;
ALTER TABLE "CashBalance" ADD CONSTRAINT "CashBalance_accountId_fkey" FOREIGN KEY ("accountId") REFERENCES "InvestmentAccount"("id") ON DELETE CASCADE; ALTER TABLE "InvestmentTransaction" ADD CONSTRAINT "InvestmentTransaction_accountId_fkey" FOREIGN KEY ("accountId") REFERENCES "InvestmentAccount"("id") ON DELETE CASCADE; ALTER TABLE "InvestmentTransaction" ADD CONSTRAINT "InvestmentTransaction_securityId_fkey" FOREIGN KEY ("securityId") REFERENCES "Security"("id") ON DELETE SET NULL;
ALTER TABLE "PortfolioSnapshot" ADD CONSTRAINT "PortfolioSnapshot_portfolioId_fkey" FOREIGN KEY ("portfolioId") REFERENCES "Portfolio"("id") ON DELETE CASCADE; ALTER TABLE "HoldingSnapshot" ADD CONSTRAINT "HoldingSnapshot_portfolioSnapshotId_fkey" FOREIGN KEY ("portfolioSnapshotId") REFERENCES "PortfolioSnapshot"("id") ON DELETE CASCADE; ALTER TABLE "HoldingSnapshot" ADD CONSTRAINT "HoldingSnapshot_accountId_fkey" FOREIGN KEY ("accountId") REFERENCES "InvestmentAccount"("id") ON DELETE CASCADE; ALTER TABLE "HoldingSnapshot" ADD CONSTRAINT "HoldingSnapshot_securityId_fkey" FOREIGN KEY ("securityId") REFERENCES "Security"("id") ON DELETE RESTRICT;
ALTER TABLE "ImportJob" ADD CONSTRAINT "ImportJob_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE; ALTER TABLE "ImportJob" ADD CONSTRAINT "ImportJob_portfolioId_fkey" FOREIGN KEY ("portfolioId") REFERENCES "Portfolio"("id") ON DELETE SET NULL; ALTER TABLE "ImportJob" ADD CONSTRAINT "ImportJob_accountId_fkey" FOREIGN KEY ("accountId") REFERENCES "InvestmentAccount"("id") ON DELETE SET NULL; ALTER TABLE "ImportJob" ADD CONSTRAINT "ImportJob_dataSourceId_fkey" FOREIGN KEY ("dataSourceId") REFERENCES "DataSource"("id") ON DELETE SET NULL;
ALTER TABLE "SyncJob" ADD CONSTRAINT "SyncJob_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE; ALTER TABLE "SyncJob" ADD CONSTRAINT "SyncJob_brokerageConnectionId_fkey" FOREIGN KEY ("brokerageConnectionId") REFERENCES "BrokerageConnection"("id") ON DELETE SET NULL; ALTER TABLE "SyncJob" ADD CONSTRAINT "SyncJob_dataSourceId_fkey" FOREIGN KEY ("dataSourceId") REFERENCES "DataSource"("id") ON DELETE SET NULL;
ALTER TABLE "PortfolioInsight" ADD CONSTRAINT "PortfolioInsight_portfolioId_fkey" FOREIGN KEY ("portfolioId") REFERENCES "Portfolio"("id") ON DELETE CASCADE; ALTER TABLE "InsightEvidence" ADD CONSTRAINT "InsightEvidence_insightId_fkey" FOREIGN KEY ("insightId") REFERENCES "PortfolioInsight"("id") ON DELETE CASCADE; ALTER TABLE "InsightEvidence" ADD CONSTRAINT "InsightEvidence_securityId_fkey" FOREIGN KEY ("securityId") REFERENCES "Security"("id") ON DELETE SET NULL;
ALTER TABLE "Watchlist" ADD CONSTRAINT "Watchlist_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE; ALTER TABLE "Watchlist" ADD CONSTRAINT "Watchlist_portfolioId_fkey" FOREIGN KEY ("portfolioId") REFERENCES "Portfolio"("id") ON DELETE SET NULL; ALTER TABLE "WatchlistSecurity" ADD CONSTRAINT "WatchlistSecurity_watchlistId_fkey" FOREIGN KEY ("watchlistId") REFERENCES "Watchlist"("id") ON DELETE CASCADE; ALTER TABLE "WatchlistSecurity" ADD CONSTRAINT "WatchlistSecurity_securityId_fkey" FOREIGN KEY ("securityId") REFERENCES "Security"("id") ON DELETE CASCADE;
ALTER TABLE "AlertRule" ADD CONSTRAINT "AlertRule_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE; ALTER TABLE "AlertRule" ADD CONSTRAINT "AlertRule_portfolioId_fkey" FOREIGN KEY ("portfolioId") REFERENCES "Portfolio"("id") ON DELETE SET NULL; ALTER TABLE "AlertRule" ADD CONSTRAINT "AlertRule_securityId_fkey" FOREIGN KEY ("securityId") REFERENCES "Security"("id") ON DELETE SET NULL; ALTER TABLE "AlertEvent" ADD CONSTRAINT "AlertEvent_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE; ALTER TABLE "AlertEvent" ADD CONSTRAINT "AlertEvent_alertRuleId_fkey" FOREIGN KEY ("alertRuleId") REFERENCES "AlertRule"("id") ON DELETE SET NULL;

-- Backfill a deterministic imported account for each existing portfolio, canonical securities, and the active imported positions.
INSERT INTO "InvestmentAccount" ("id", "userId", "portfolioId", "providerAccountId", "name", "accountType", "currency", "status", "isIncludedInAnalysis", "createdAt", "updatedAt") SELECT 'legacy-account-' || "id", "userId", "id", 'legacy-' || "id", 'Imported positions', 'BROKERAGE', "currency", 'ACTIVE', true, NOW(), NOW() FROM "Portfolio" ON CONFLICT ("id") DO NOTHING;
INSERT INTO "Security" ("id", "canonicalSymbol", "name", "securityType", "currency", "sector", "createdAt", "updatedAt") SELECT 'legacy-security-' || md5("symbol"), "symbol", COALESCE(MAX("companyName"), "symbol"), 'OTHER', 'USD', MAX("sector"), NOW(), NOW() FROM "ImportedHolding" GROUP BY "symbol" ON CONFLICT ("canonicalSymbol") DO NOTHING;
INSERT INTO "Holding" ("id", "accountId", "securityId", "quantity", "averageCost", "costBasis", "currentPrice", "marketValue", "currency", "asOfDate", "source", "createdAt", "updatedAt") SELECT 'legacy-holding-' || h."id", 'legacy-account-' || h."portfolioId", s."id", h."shares", h."costBasis", CASE WHEN h."costBasis" IS NULL THEN NULL ELSE h."costBasis" * h."shares" END, h."currentPrice", h."marketValue", 'USD', i."importedAt", 'CSV_IMPORT', NOW(), NOW() FROM "ImportedHolding" h JOIN "ImportHistory" i ON i."id" = h."importId" AND i."isActive" = true JOIN "Security" s ON s."canonicalSymbol" = h."symbol" ON CONFLICT ("accountId", "securityId") DO UPDATE SET "quantity" = EXCLUDED."quantity", "averageCost" = EXCLUDED."averageCost", "costBasis" = EXCLUDED."costBasis", "currentPrice" = EXCLUDED."currentPrice", "marketValue" = EXCLUDED."marketValue", "asOfDate" = EXCLUDED."asOfDate", "updatedAt" = NOW();
