"use client";
import { useRef, useState } from "react";
import { parsePortfolioCsv } from "@/lib/import/csv";
import type { ParseResult } from "@/lib/import/types";
const MAX_BYTES = 5 * 1024 * 1024;
export function PortfolioImportDialog({ onComplete, portfolioId }: { onComplete(): void; portfolioId?: string }) {
 const input=useRef<HTMLInputElement>(null); const [open,setOpen]=useState(false); const [file,setFile]=useState<File|null>(null); const [data,setData]=useState<ParseResult|null>(null); const [error,setError]=useState(""); const [saving,setSaving]=useState(false);
 async function choose(f?:File){if(!f)return;setError("");if(!f.name.toLowerCase().endsWith(".csv"))return setError("Please choose a CSV file.");if(f.size>MAX_BYTES)return setError("Files must be 5 MB or smaller.");setFile(f);setData(parsePortfolioCsv(await f.text()));}
 function remove(index:number){setData(x=>x?{...x,rows:x.rows.filter((_,i)=>i!==index)}:x)}
 async function save(){if(!file||!data)return;setSaving(true);setError("");try{const response=await fetch("/api/imports",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({portfolioId,portfolioName:"My Portfolio",broker:data.broker,fileName:file.name,rawCsv:await file.text(),headers:data.headers,warnings:data.warnings,rows:data.rows})});const result=await response.json();if(!response.ok)throw new Error(result.error);setOpen(false);setFile(null);setData(null);onComplete()}catch(e){setError(e instanceof Error?e.message:"Import failed.")}finally{setSaving(false)}}
 const invalid=!!data?.fileErrors.length||!!data?.rows.some(row=>row.errors.length);
 return <><button onClick={()=>setOpen(true)} className="rounded-xl bg-slate-950 px-4 py-3 text-sm font-semibold text-white">Upload portfolio ↑</button>{open&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/45 p-4"><div className="max-h-[92vh] w-full max-w-5xl overflow-auto rounded-2xl bg-white p-6 shadow-2xl"><div className="flex justify-between"><div><h2 className="text-xl font-semibold">Import your portfolio</h2><p className="mt-1 text-sm text-slate-500">CSV only · up to 10,000 holdings.</p></div><button onClick={()=>setOpen(false)}>×</button></div>{!file?<div onClick={()=>input.current?.click()} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();choose(e.dataTransfer.files[0])}} className="mt-6 cursor-pointer rounded-2xl border-2 border-dashed border-emerald-300 bg-emerald-50 p-14 text-center"><b>Drop your broker CSV here</b><p className="mt-2 text-sm text-slate-500">or click to browse</p><input ref={input} className="hidden" type="file" accept=".csv,text/csv" onChange={e=>choose(e.target.files?.[0])}/></div>:<div className="mt-6"><div className="flex justify-between rounded-xl bg-slate-50 p-4 text-sm"><span><b>{file.name}</b> · {Math.ceil(file.size/1024)} KB</span><button className="text-emerald-700" onClick={()=>{setFile(null);setData(null)}}>Replace</button></div>{data&&<><p className="mt-4 text-sm"><b>{data.broker}</b> detected · {data.rows.length} rows</p>{[...data.fileErrors,...data.warnings].map(x=><p className="mt-3 rounded bg-amber-50 p-3 text-sm text-amber-800" key={x}>{x}</p>)}<div className="mt-5 overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left text-slate-500">{["Ticker","Company","Shares","Avg. cost","Market value","Sector",""].map(x=><th className="p-2" key={x}>{x}</th>)}</tr></thead><tbody>{data.rows.map((row,index)=><tr className={row.errors.length?"bg-red-50":"border-t"} key={row.rowNumber}><td className="p-2">{row.symbol}</td><td className="p-2">{row.companyName}</td><td className="p-2">{row.shares}</td><td className="p-2">{row.costBasis}</td><td className="p-2">{row.marketValue}</td><td className="p-2">{row.sector}</td><td className="p-2"><button onClick={()=>remove(index)} className="text-red-600">Remove</button>{row.errors.map(e=><p className="text-xs text-red-700" key={e.message}>Row {row.rowNumber}: {e.message}</p>)}</td></tr>)}</tbody></table></div></>}</div>}{error&&<p className="mt-4 text-sm text-red-700">{error}</p>}<div className="mt-6 flex justify-end gap-3"><button onClick={()=>setOpen(false)}>Cancel</button><button disabled={!data||invalid||saving} onClick={save} className="rounded-xl bg-emerald-600 px-4 py-3 text-sm font-semibold text-white disabled:opacity-40">{saving?"Saving…":"Approve import"}</button></div></div></div>}</>;
}
