"use client";

import { useEffect, useState } from "react";

type Dashboard = {
  portfolio: { name: string; holdingCount: number; totalValue: number; diversificationScore: number; importedAt: string };
  allocation: Array<{ label: string; percentage: number }>;
  holdings: Array<{ symbol: string; companyName: string | null; marketValue: number; allocationPercent: number; sector: string | null }>;
  analytics: { insights: Array<{ id: string; title: string; summary: string; severity: string }>; researchAreas: string[]; dataQuality: { message: string; costBasisCoveragePercent: number; classifiedValuePercent: number } };
};
const money = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 });

export function PortfolioAnalysisReport() {
  const [data, setData] = useState<Dashboard | null>(null);
  useEffect(() => { void fetch("/api/portfolios/dashboard", { cache: "no-store" }).then((r) => r.json()).then((r) => setData(r.dashboard ?? null)); }, []);
  if (!data) return <main className="grid min-h-screen place-items-center bg-stone-50 text-slate-500">Loading portfolio report…</main>;
  return <main className="min-h-screen bg-stone-50 px-5 py-10 text-slate-900 sm:px-8"><article className="mx-auto max-w-5xl"><header className="border-b border-slate-300 pb-10"><p className="font-mono text-xs uppercase tracking-[.2em] text-emerald-700">AlphaPilot portfolio review</p><h1 className="mt-3 text-4xl font-semibold tracking-tight">{data.portfolio.name}</h1><p className="mt-3 max-w-2xl text-slate-600">A deterministic review of imported holdings. It identifies questions to investigate; it does not provide investment advice.</p><dl className="mt-7 grid gap-5 sm:grid-cols-3"><Fact label="Imported portfolio value" value={money.format(data.portfolio.totalValue)} /><Fact label="Diversification signal" value={`${data.portfolio.diversificationScore}/100`} /><Fact label="As of" value={new Date(data.portfolio.importedAt).toLocaleDateString()} /></dl></header><ReportSection title="Executive review" summary="What stands out in the current portfolio composition."><div className="space-y-3">{data.analytics.insights.map((i) => <div key={i.id} className="border-l-2 border-emerald-500 pl-4"><strong>{i.title}</strong><p className="mt-1 text-slate-600">{i.summary}</p></div>)}</div></ReportSection><ReportSection title="Exposure and concentration" summary="Where the portfolio is currently concentrated."><div className="grid gap-6 md:grid-cols-2"><List title="Sector exposure" rows={data.allocation.map((x) => `${x.label}: ${x.percentage.toFixed(1)}%`)} /><List title="Largest positions" rows={data.holdings.slice(0, 10).map((x) => `${x.symbol} — ${x.allocationPercent.toFixed(1)}% of portfolio`)} /></div></ReportSection><ReportSection title="Research queue" summary="Questions generated from deterministic portfolio signals."><ul className="space-y-3">{data.analytics.researchAreas.map((x) => <li key={x}>• {x}</li>)}</ul></ReportSection><ReportSection title="Data quality and methodology" summary="What this review knows and what remains unavailable."><p>{data.analytics.dataQuality.message}</p><p className="mt-3">Sector classification covers {data.analytics.dataQuality.classifiedValuePercent.toFixed(1)}% of imported value; cost basis covers {data.analytics.dataQuality.costBasisCoveragePercent.toFixed(1)}%.</p></ReportSection><ReportSection title="Advanced review" summary="Historical, tax, and risk sections activate only when their source data exists."><List title="Awaiting source data" rows={["Tax lots and realized-gain history", "Historical portfolio snapshots and benchmark returns", "Licensed security, event, and fund-constituent data", "Dividend and corporate-action history"]} /></ReportSection></article></main>;
}
function Fact({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs uppercase tracking-wide text-slate-500">{label}</dt><dd className="mt-1 text-xl font-semibold">{value}</dd></div>; }
function ReportSection({ title, summary, children }: { title: string; summary: string; children: React.ReactNode }) { return <details open className="border-b border-slate-200 py-8"><summary className="cursor-pointer list-none"><h2 className="text-2xl font-semibold">{title}</h2><p className="mt-2 text-slate-600">{summary}</p></summary><div className="mt-6 text-sm leading-6 text-slate-700">{children}</div></details>; }
function List({ title, rows }: { title: string; rows: string[] }) { return <div><h3 className="font-semibold">{title}</h3><ul className="mt-2 space-y-1 text-slate-600">{rows.map((row) => <li key={row}>{row}</li>)}</ul></div>; }
